image: node:10

stages:
    - build
    - test

cache:
    paths:
        - node_modules/

install_dependencies:
    state: build
    script:
        - npm install
    artifacts:
        paths:
            - node_modules/

test:
    stage: test
    script:
        - npm test
